### ISSUE TITLE
无法正常连接

### ISSUE THREAD

**Issue by Daveshammer** [czqu/RemoteFingerUnlock#1]
点击“二维码”，windbg会出现
onecore\net\netprofiles\service\src\nsp\dll\namespaceserviceprovider.cpp(613)\nlansp_c.dll!00007FFA5048F6BD: (caller: 00007FFA6491ACF6) LogHr(1) tid(cf00) 8007277C 此服务不存在。在指定的命名空间中找不这个服务。

**Comment by czqu** [comment]
> 点击“二维码”，windbg会出现 onecore\net\netprofiles\service\src\nsp\dll\namespaceserviceprovider.cpp(613)\nlansp_c.dll!00007FFA5048F6BD: (caller: 00007FFA6491ACF6) LogHr(1) tid(cf00) 8007277C 此服务不存在。在指定的命名空间中找不这个服务。

Recommend upgrading to version 3.4.0.0 or above.

**Comment by czqu** [comment]
The issue no longer exists in the new version.
