### ISSUE TITLE
最小化发生异常

### ISSUE THREAD

**Issue by Daveshammer** [czqu/RemoteFingerUnlock#2]
ModLoad: 00007ffa`25960000 00007ffa`25970000   C:\Program Files\RemoteFingerUnlockModule\BluetoothExt.dll
ModLoad: 00007ff9`03200000 00007ff9`03ed3000   C:\Program Files\RemoteFingerUnlockModule\NetExtension.dll
(32f4.ac68): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** WARNING: Unable to verify timestamp for C:\Program Files\RemoteFingerUnlockModule\NetExtension.dll

**Comment by czqu** [comment]
> ModLoad: 00007ffa`25960000 00007ffa`25970000 C:\Program Files\RemoteFingerUnlockModule\BluetoothExt.dll ModLoad: 00007ff9`03200000 00007ff9`03ed3000 C:\Program Files\RemoteFingerUnlockModule\NetExtension.dll (32f4.ac68): Access violation - code c0000005 (first chance) First chance exceptions are reported before any exception handling. This exception may be expected and handled. *** WARNING: Unable to verify timestamp for C:\Program Files\RemoteFingerUnlockModule\NetExtension.dll

Recommend upgrading to version 3.4.0.0 or above.

**Comment by czqu** [comment]
The issue no longer exists in the new version.
